
import javax.swing.JOptionPane;

public class Calculadora extends javax.swing.JFrame {

    private Double n1 = 0d;
    private Double n2 = 0d;
    private Character opc = '+';
    private boolean limparVisorAuto = false;
    
    
    public Calculadora() {
        initComponents();
        jtfVisor.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbtnPositivoNegativo = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn1Sobre = new javax.swing.JButton();
        jbtnAdicao = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnMultiplicar = new javax.swing.JButton();
        jbtnPonto = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtnCE = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnPorcentagem = new javax.swing.JButton();
        jbtnDividir = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtnSubtracao = new javax.swing.JButton();
        jbtnRaizQuadrada = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtnIgual = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jtfVisor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora - versão 1.0.0");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jbtnPositivoNegativo.setForeground(new java.awt.Color(204, 0, 0));
        jbtnPositivoNegativo.setText("±");
        jbtnPositivoNegativo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPositivoNegativo.setFocusable(false);
        jbtnPositivoNegativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPositivoNegativoActionPerformed(evt);
            }
        });

        jbtnC.setForeground(new java.awt.Color(204, 0, 0));
        jbtnC.setText("C");
        jbtnC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnC.setFocusable(false);
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });

        jbtn3.setForeground(new java.awt.Color(0, 0, 204));
        jbtn3.setText("3");
        jbtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn3.setFocusable(false);
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });

        jbtn1Sobre.setForeground(new java.awt.Color(204, 0, 0));
        jbtn1Sobre.setText("1/x");
        jbtn1Sobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn1Sobre.setFocusable(false);
        jbtn1Sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1SobreActionPerformed(evt);
            }
        });

        jbtnAdicao.setForeground(new java.awt.Color(204, 0, 0));
        jbtnAdicao.setText("+");
        jbtnAdicao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnAdicao.setFocusable(false);
        jbtnAdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdicaoActionPerformed(evt);
            }
        });

        jbtn2.setForeground(new java.awt.Color(0, 0, 204));
        jbtn2.setText("2");
        jbtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn2.setFocusable(false);
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });

        jbtnDelete.setForeground(new java.awt.Color(204, 0, 0));
        jbtnDelete.setText("DEL");
        jbtnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDelete.setFocusable(false);
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        jbtnMultiplicar.setForeground(new java.awt.Color(204, 0, 0));
        jbtnMultiplicar.setText("*");
        jbtnMultiplicar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnMultiplicar.setFocusable(false);
        jbtnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMultiplicarActionPerformed(evt);
            }
        });

        jbtnPonto.setForeground(new java.awt.Color(0, 0, 204));
        jbtnPonto.setText(".");
        jbtnPonto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPonto.setFocusable(false);
        jbtnPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPontoActionPerformed(evt);
            }
        });

        jbtn6.setForeground(new java.awt.Color(0, 0, 204));
        jbtn6.setText("6");
        jbtn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn6.setFocusable(false);
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });

        jbtn1.setForeground(new java.awt.Color(0, 0, 204));
        jbtn1.setText("1");
        jbtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn1.setFocusable(false);
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });

        jbtnCE.setForeground(new java.awt.Color(204, 0, 0));
        jbtnCE.setText("CE");
        jbtnCE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnCE.setFocusable(false);
        jbtnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCEActionPerformed(evt);
            }
        });

        jbtn0.setForeground(new java.awt.Color(0, 0, 204));
        jbtn0.setText("0");
        jbtn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn0.setFocusable(false);
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });

        jbtnPorcentagem.setForeground(new java.awt.Color(204, 0, 0));
        jbtnPorcentagem.setText("%");
        jbtnPorcentagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPorcentagem.setFocusable(false);
        jbtnPorcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPorcentagemActionPerformed(evt);
            }
        });

        jbtnDividir.setForeground(new java.awt.Color(204, 0, 0));
        jbtnDividir.setText("/");
        jbtnDividir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDividir.setFocusable(false);
        jbtnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDividirActionPerformed(evt);
            }
        });

        jbtn9.setForeground(new java.awt.Color(0, 0, 204));
        jbtn9.setText("9");
        jbtn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn9.setFocusable(false);
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });

        jbtnSubtracao.setForeground(new java.awt.Color(204, 0, 0));
        jbtnSubtracao.setText("-");
        jbtnSubtracao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSubtracao.setFocusable(false);
        jbtnSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubtracaoActionPerformed(evt);
            }
        });

        jbtnRaizQuadrada.setForeground(new java.awt.Color(204, 0, 0));
        jbtnRaizQuadrada.setText("√");
        jbtnRaizQuadrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnRaizQuadrada.setFocusable(false);
        jbtnRaizQuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRaizQuadradaActionPerformed(evt);
            }
        });

        jbtn5.setForeground(new java.awt.Color(0, 0, 204));
        jbtn5.setText("5");
        jbtn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn5.setFocusable(false);
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });

        jbtn8.setForeground(new java.awt.Color(0, 0, 204));
        jbtn8.setText("8");
        jbtn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn8.setFocusable(false);
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });

        jbtnIgual.setForeground(new java.awt.Color(204, 0, 0));
        jbtnIgual.setText("=");
        jbtnIgual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnIgual.setFocusable(false);
        jbtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIgualActionPerformed(evt);
            }
        });

        jbtn7.setForeground(new java.awt.Color(0, 0, 204));
        jbtn7.setText("7");
        jbtn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn7.setFocusable(false);
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });

        jbtn4.setForeground(new java.awt.Color(0, 0, 204));
        jbtn4.setText("4");
        jbtn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn4.setFocusable(false);
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnCE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbtn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbtnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn1Sobre, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbtnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jbtnPositivoNegativo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtnRaizQuadrada, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtnSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtnAdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnC)
                            .addComponent(jbtnPositivoNegativo)
                            .addComponent(jbtnRaizQuadrada))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn9)
                            .addComponent(jbtnDividir)
                            .addComponent(jbtnPorcentagem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn6)
                            .addComponent(jbtnMultiplicar)
                            .addComponent(jbtn1Sobre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtn3)
                                    .addComponent(jbtnSubtracao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtnPonto)
                                    .addComponent(jbtnAdicao)))
                            .addComponent(jbtnIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnDelete)
                            .addComponent(jbtnCE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn7)
                            .addComponent(jbtn8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn5)
                            .addComponent(jbtn4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn1)
                            .addComponent(jbtn2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn0)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jtfVisor.setEditable(false);
        jtfVisor.setBackground(new java.awt.Color(255, 255, 255));
        jtfVisor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtfVisor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfVisor.setText("0");
        jtfVisor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtfVisor.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jtfVisor.setSelectionColor(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfVisor)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jtfVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
        );

        
        jMenu2.setMnemonic('s');
        jMenu2.setText("Sobre");

        jMenuItem2.setText("       Equipe: Josuel");
        jMenuItem2.setSize(30,32);
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        limparVisor();
        jtfVisor.setText(jtfVisor.getText().equals("0") ? "" : jtfVisor.getText());
        jtfVisor.setText(jtfVisor.getText() + "0");
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        limparVisor();
        jtfVisor.setText(jtfVisor.getText().equals("0") ? "" : jtfVisor.getText());
        jtfVisor.setText(jtfVisor.getText() + "1");
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        limparVisor();
        jtfVisor.setText(jtfVisor.getText().equals("0") ? "" : jtfVisor.getText());
        jtfVisor.setText(jtfVisor.getText() + "2");
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        limparVisor();
        jtfVisor.setText(jtfVisor.getText().equals("0") ? "" : jtfVisor.getText());
        jtfVisor.setText(jtfVisor.getText() + "3");
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        limparVisor();
        jtfVisor.setText(jtfVisor.getText().equals("0") ? "" : jtfVisor.getText());
        jtfVisor.setText(jtfVisor.getText() + "4");
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        limparVisor();
        jtfVisor.setText(jtfVisor.getText().equals("0") ? "" : jtfVisor.getText());
        jtfVisor.setText(jtfVisor.getText() + "5");
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        limparVisor();
        jtfVisor.setText(jtfVisor.getText().equals("0") ? "" : jtfVisor.getText());
        jtfVisor.setText(jtfVisor.getText() + "6");
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        limparVisor();
        jtfVisor.setText(jtfVisor.getText().equals("0") ? "" : jtfVisor.getText());
        jtfVisor.setText(jtfVisor.getText() + "7");
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        limparVisor();
        jtfVisor.setText(jtfVisor.getText().equals("0") ? "" : jtfVisor.getText());
        jtfVisor.setText(jtfVisor.getText() + "8");
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        limparVisor();
        jtfVisor.setText(jtfVisor.getText().equals("0") ? "" : jtfVisor.getText());
        jtfVisor.setText(jtfVisor.getText() + "9");
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtnPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPontoActionPerformed
        if (!jtfVisor.getText().matches(".*\\..*")) {
            jtfVisor.setText(jtfVisor.getText() + ".");
        }
    }//GEN-LAST:event_jbtnPontoActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        if (!jtfVisor.getText().equals("0")) {

            jtfVisor.setText(jtfVisor.getText().substring(0, jtfVisor.getText().length() - 1));

            if (jtfVisor.getText().isEmpty()) {
                jtfVisor.setText("0");
            }
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnPositivoNegativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPositivoNegativoActionPerformed
        if ((Double.valueOf(jtfVisor.getText())) > 0) {
            jtfVisor.setText("-" + jtfVisor.getText());
        }
        else {
            jtfVisor.setText(jtfVisor.getText().replace("-", ""));
        }
    }//GEN-LAST:event_jbtnPositivoNegativoActionPerformed

    private void jbtnRaizQuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRaizQuadradaActionPerformed
        if (Double.valueOf(jtfVisor.getText()) >= 0) {
            jtfVisor.setText("" + Math.sqrt(Double.valueOf(jtfVisor.getText())));
            limparVisorAuto = true;
        }
        else {
            JOptionPane.showMessageDialog(null, "RAIZ NÃO POSSÍVEL", "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnRaizQuadradaActionPerformed

    private void jbtnPorcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPorcentagemActionPerformed
        jtfVisor.setText("" + (Double.valueOf(jtfVisor.getText()) / 100d));
        limparVisorAuto = true;
    }//GEN-LAST:event_jbtnPorcentagemActionPerformed

    private void jbtn1SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1SobreActionPerformed
        jtfVisor.setText("" + (1d / Double.valueOf(jtfVisor.getText())));
        limparVisorAuto = true;
    }//GEN-LAST:event_jbtn1SobreActionPerformed

    private void jbtnAdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdicaoActionPerformed
        armazenar('+');
    }//GEN-LAST:event_jbtnAdicaoActionPerformed

    private void jbtnSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubtracaoActionPerformed
        armazenar('-');
    }//GEN-LAST:event_jbtnSubtracaoActionPerformed

    private void jbtnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultiplicarActionPerformed
        armazenar('*');
    }//GEN-LAST:event_jbtnMultiplicarActionPerformed

    private void jbtnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDividirActionPerformed
        armazenar('/');
    }//GEN-LAST:event_jbtnDividirActionPerformed

    private void jbtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCEActionPerformed
        jtfVisor.setText("0");
    }//GEN-LAST:event_jbtnCEActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        n1 = 0d;
        n2 = 0d;
        opc = '+';
        jtfVisor.setText("0");
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIgualActionPerformed
        verResultado();
    }//GEN-LAST:event_jbtnIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try{
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equalsIgnoreCase(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }catch(Exception erro){
            
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn1Sobre;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnAdicao;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnCE;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnDividir;
    private javax.swing.JButton jbtnIgual;
    private javax.swing.JButton jbtnMultiplicar;
    private javax.swing.JButton jbtnPonto;
    private javax.swing.JButton jbtnPorcentagem;
    private javax.swing.JButton jbtnPositivoNegativo;
    private javax.swing.JButton jbtnRaizQuadrada;
    private javax.swing.JButton jbtnSubtracao;
    private javax.swing.JTextField jtfVisor;
    // End of variables declaration//GEN-END:variables

    private void armazenar(Character c) {
        
        if(n1 == 0d){
            opc = c;
            n1 = Double.parseDouble(jtfVisor.getText());
            jtfVisor.setText("0");
        }
        else
        if(n2 == 0d){
            opc = c;
            n2 = Double.parseDouble(jtfVisor.getText());
            jtfVisor.setText("0");
        }
        else{
            calcular();
            armazenar(c);
        }
    }

    private void calcular() {
        switch (opc) {
            case '+':
                n1 = n1 + n2;
            break;
            
            case '/':
                n1 = n1 / n2;
            break;
            
            case '-':
                n1 = n1 - n2;
            break;
            
            case '*':
                n1 = n1 * n2;
            break;
        }
        
        n2 = 0d;
    }
    
    private void limparVisor(){
        
        if(!limparVisorAuto){
            return;
        }
        else{
            jtfVisor.setText("0");
        }
        
        limparVisorAuto = false;
    }

    private void verResultado() {
        
        if(n1 != 0 && n2 != 0){
            calcular();
        }
        
        n2 = Double.parseDouble(jtfVisor.getText());
        calcular();
        
        jtfVisor.setText(n1+"");
        limparVisorAuto = true;
        n1 = 0d;
        n2 = 0d;
        opc = '+';
    }
    

}